### ISSUE TITLE
acme-challenge not found after upgrade to 0.13.0

### ISSUE THREAD

**Issue by sweet-greg** [GUI/lua-resty-auto-ssl#194]
I'm unable to request a new certificate after upgrading to v0.13.0

```
{
"type": "urn:ietf:params:acme:error:unauthorized",
"detail": "Invalid response from http://example.domain.com/.well-known/acme-challenge/qTUHKq1CHY2Hx4MI8JfHu2_9I_n_JtmoGRr0Nnk9d5k [my.ip.address.here]: \"\u003chtml\u003e\\r\\n\u003chead\u003e\u003ctitle\u003e404 Not Found\u003c/title\u003e\u003c/head\u003e\\r\\n\u003cbody\u003e\\r\\n\u003ccenter\u003e\u003ch1\u003e404 Not Found\u003c/h1\u003e\u003c/center\u003e\\r\\n\u003chr\u003e\u003ccenter\
"status": 403
},
```
Visiting the url returns a 404.

Worked fine before the upgrade (v0.12.0 with [this hotfix](https://github.com/GUI/lua-resty-auto-ssl/issues/192#issuecomment-535849941)) just yesterday.

Does anyone have an idea why this is happening?

**Comment by GUI** [comment]
Sorry for the trouble! Although, this is certainly odd, since I'm having a hard time thinking of how the upgrades would be leading to 404s for the acme-challenge request. The upgrade does means the ACMEv2 protocol is being used by default now, but I didn't think that would make a difference here.

In order to debug this, here's a few things I can think to try:

- Can you verify whether the `http://example.domain.com/.well-known/acme-challenge/qTUHKq1CHY2Hx4MI8JfHu2_9I_n_JtmoGRr0Nnk9d5k` request shows up in your nginx `access.log` (assuming you have that enabled)? I just want to double check these requests are hitting your nginx server as expected.
- If they are, you could try editing your nginx's HTTP config to add a bit of debugging to the challenge location, with something like:
    ```nginx
    location /.well-known/acme-challenge/ {
      content_by_lua_block {
        ngx.log(ngx.ERR, "DEBUG lua-resty-auto-ssl: acme-challenge")
        ngx.log(ngx.ERR, "DEBUG lua-resty-auto-ssl: acme-challenge host=", ngx.var.host)
        auto_ssl:challenge_server()
      }
    }
    ```

  If you then make the acme challenge request again (either manually, or by triggering a real certificate request), do you see these debug lines show up in your nginx `error.log` file?
- What storage adapter are you using? Can you manually inspect it to see if the `example.domain.com:qTUHKq1CHY2Hx4MI8JfHu2_9I_n_JtmoGRr0Nnk9d5k` key is present in it? Give a shout if you need any help in finding where this might be stored depending on the adapter.
- If you tweak your nginx [`error_log` level](http://nginx.org/en/docs/ngx_core_module.html#error_log) to `notice`, this will print out more information about the various steps taking place during certificate registration in your nginx `error.log`. Do any other errors or items stand out in there?

**Comment by sweet-greg** [comment]
I'm sorry @GUI 
Seems it was my mistake completely unrelated to the upgrade!
