### ISSUE TITLE
No simultaneous certificate creation?

### ISSUE THREAD

**Issue by Eihrister** [GUI/lua-resty-auto-ssl#24]
Hi,

I think this might be due to letsencrypt.sh limitations and/or Let's Encrypt themselves, but: If I open example.com in one tab, and open www.example.com in another tab while it's creating the certificate/key pair for example.com, www.example.com simply returns the fallback cert. Refreshing after example.com's creation is done, makes it create and return the cert for www.example.com just fine.

Daniël

**Comment by Eihrister** [comment]
This limitation is probably coming from vendor/letsencrypt.sh (check for lockfile).

**Comment by GUI** [comment]
Thank you very much for tracking this down!

I believe this should be fixed in v0.10.0 by disabling dehydrated's locking mechanism altogether (but this is unfortunately a bit difficult to add tests for to our test suite). Since we already do our own per-domain locking (using the storage adapter so the locking can be distributed across servers), dehydrated's own local locking should have been redundant. So for now, I've just disabled dehydrated's local locking completely, but if your dehydrated pull request gets merged, we can re-enable it (if we want the double locking mechanism). Thanks again!
