### ISSUE TITLE
same possible for the Mail Protocol?

### ISSUE THREAD

**Issue by musab1** [GUI/lua-resty-auto-ssl#31]
As more and more Mail Clients also Support SNI when talking to the MailServer 
i thought it would be nice to got the same for the Mail Part of Nginx/Reverse Proxy.

I got a test setup, and the https part works perfectly.

Simply doing this part in the Mail Section of the Config:

   ssl_certificate_by_lua_block {
      auto_ssl:ssl_certificate()
    }

gives a 
nginx: [emerg] "ssl_certificate_by_lua_block" directive is not allowed here in /usr/local/openresty/nginx/conf/nginx.conf:92
back. 

is it in anyway possible to use the same mechanics to be able to present the mail client the right certificate?

**Comment by GUI** [comment]
Currently, I don't think will be possible at our layer, since we'd need support for this from OpenResty.

I'm not sure about direct integration into nginx's `mail` configuration, but one possibility that might be on the horizon would be integrating this with nginx's `stream` config, where `ssl_certificate_by_lua` integration is [on the TODO list](https://github.com/openresty/stream-lua-nginx-module#todo). Once this was implemented, then I think you could achieve mail support by putting an nginx stream proxy in front of your mail server (since streams are just a generic TCP proxy, so I think it should proxy to a mail server without issue).

However, I'm not sure when `ssl_certificate_by_lua` within `stream` might be implemented (or if they're looking for the community to submit a pull request with that functionality). You might try the [openresty-en](https://groups.google.com/group/openresty-en) mailing list to discuss further.

**Comment by GUI** [comment]
I'm going to go ahead and close this, since there's not much we can do about it now. But if `stream` gains support for `ssl_certificate_by_lua`, we can revisit.

**Comment by musab1** [comment]
Hallo @GUI 

i think now it should be possible?

i've tried it really hard - but no success with stream and resty-auto-ssl

as far i know ssl_certificate_by_lua know works with stream. 
guess i am just to stupid. 

should i create a new issue?
