### ISSUE TITLE
Make it possible to change hook-port

### ISSUE THREAD

**Issue by luto** [GUI/lua-resty-auto-ssl#34]
Currently the hook-port is hard coded to be `8999`. Lua-resty-auto-ssl should implement changing this port to another value (e.g. to a lower port only root can bind to), while defaulting to `8999` so we don't break existing installations.

TODO:
- [ ] add a new parameter named `hook_server_port`
  - [ ] check that the new parameter contains a number below 65536
  - [ ] make it default to `8999`
- [ ] respect value in [letsencrypt_hooks#L20](https://github.com/GUI/lua-resty-auto-ssl/blob/master/lib/resty/auto-ssl/shell/letsencrypt_hooks#L20)
- [ ] respect value in [letsencrypt_hooks#L31](https://github.com/GUI/lua-resty-auto-ssl/blob/master/lib/resty/auto-ssl/shell/letsencrypt_hooks#L31)
- [ ] write tests
  - [ ] change the port, plus invalid values
  - [ ] default to `8999`
- [ ] document new parameter in README

What do you think about this?

**Comment by GUI** [comment]
Allowing this to be more configurable is a good idea. Your outline seems to cover everything I can think of.

I think the main trick is getting the configuration variable passed into the `letsencrypt_hooks` bash shell script, but I think we could pass that along via an environment variable, similar to how we pass along the `HOOK_SECRET`.

Then I think whatever port you want to use would still have to be defined twice--once in the lua config and once in the nginx `server` `listen` definition. Since the nginx `listen` directive has to be manually assigned (it can't accept variables), I think that's the best we can do, but that would still make it configurable, which would be a nice improvement.

If you'd like to submit a pull request for this, it would certainly be welcome. Otherwise, I can also look into implementing this sometime (but I'm not sure when that would be).

Thanks for the idea!
