### ISSUE TITLE
Latest private key file name does not exist.

### ISSUE THREAD

**Issue by Vad1mo** [GUI/lua-resty-auto-ssl#37]
According to [this code](https://github.com/GUI/lua-resty-auto-ssl/blob/master/lib/resty/auto-ssl/storage.lua#L55), I was expecting to see here the `privkey-latest.pem` and `cert-latest.pem`cert file, but they are not there.
 
I need to get the private key/cert to be also used in another service for token  encryption.

Also why are there new private keys created for the same domain?

```
/ # ls -la /tmp/letsencrypt/certs/app.domain.com/
total 40
drwx------    2 nobody   nobody        4096 Jan  5 23:34 .
drwx------    3 nobody   nobody        4096 Jan  5 23:31 ..
-rw-------    1 nobody   nobody        1695 Jan  5 23:32 cert-1483659118.csr
-rw-------    1 nobody   nobody           0 Jan  5 23:32 cert-1483659118.pem
-rw-------    1 nobody   nobody        1695 Jan  5 23:32 cert-1483659135.csr
-rw-------    1 nobody   nobody           0 Jan  5 23:32 cert-1483659135.pem
-rw-------    1 nobody   nobody        1695 Jan  5 23:34 cert-1483659255.csr
-rw-------    1 nobody   nobody           0 Jan  5 23:34 cert-1483659255.pem
-rw-------    1 nobody   nobody        1695 Jan  5 23:34 cert-1483659261.csr
-rw-------    1 nobody   nobody           0 Jan  5 23:34 cert-1483659261.pem
-rw-------    1 nobody   nobody        3243 Jan  5 23:32 privkey-1483659118.pem
-rw-------    1 nobody   nobody        3247 Jan  5 23:32 privkey-1483659135.pem
-rw-------    1 nobody   nobody        3243 Jan  5 23:34 privkey-1483659255.pem
-rw-------    1 nobody   nobody        3243 Jan  5 23:34 privkey-1483659261.pem
```

**Comment by GUI** [comment]
That directory is the temporary directory the dehydrated script uses when registering the cert. If you're looking for where lua-resty-auto-ssl stores its certs for persistent storage (and that `latest` symlink), then it should be in here: `/etc/resty-auto-ssl/storage/file/` (assuming you're using the file storage and the default `dir` setting).

Regarding the private keys, the default behavior of dehydrated (and most Let's Encrypt clients, I believe) is to generate a new private key on each renewal. Since things are fully automated, rotating the private key is usually a good idea. Here's a more detailed explanation: https://community.letsencrypt.org/t/do-new-private-keys-get-regenerated-on-certificate-renewal/21486/4
