### ISSUE TITLE
openresty with auto ssl + PHP + FPM

### ISSUE THREAD

**Issue by paulocastellano** [GUI/lua-resty-auto-ssl#52]
Hello, 

I managed to make auto run ssl with simple html, does anyone know how I can make it work with php and fpm?

**Comment by gjongenelen** [comment]
You will need to place the following code in your nginx.conf within the server-block
`location ~ \.php$ {
  fastcgi_split_path_info  ^(.+\.php)(/.+)$;
  fastcgi_pass                  phpupstream;
  include                           fastcgi_params;
  fastcgi_param               PATH_INFO           $fastcgi_path_info;
}`

**Comment by GUI** [comment]
I'm going to go ahead and close this. Running PHP shouldn't be any different with this module installed than otherwise in nginx, so this is a bit outside of scope for this project. But @gjongenelen's provides a good reference to a basic configuration (thanks!), or googling around for nginx and PHP FPM guides should result in lots of more detailed information.
