### ISSUE TITLE
installing invalid certificate

### ISSUE THREAD

**Issue by discoursehosting** [GUI/lua-resty-auto-ssl#55]
We encountered a problem when issuing a new certificate failed, but the certificate was installed anyway.
Second issue is: why was it requesting a new certificate? The previous one was only 18 hours old.

```
2017/04/04 00:01:48 [error] 2398#0: *1352113 [lua] ssl_certificate.lua:88: issue_cert(): auto-ssl: issuing new certificate failed: dehydrated succeeded, but no certs present, context: ssl_certificate_by
_lua*, client: 67.205.xx.xxx, server: 0.0.0.0:443
2017/04/04 00:01:48 [error] 2398#0: *1352113 [lua] ssl_certificate.lua:247: auto-ssl: could not get certificate for www.mydomain.com  - using fallback - failed to get or issue certificate, context: ssl_certificate_by_lua*, client: 67.205.xx.xxx, server: 0.0.0.0:443
```

```
root@prof394:/etc/resty-auto-ssl/storage/file# ls -l
total 20
-rw-rw-rw- 1 www-data www-data 9571 Apr  3 05:56 www.mydomain.com%3A1491199011707
-rw-rw-rw- 1 www-data www-data   51 Apr  4 00:01 www.mydomain.com%3A1491264107999
-rw-rw-rw- 1 www-data www-data   51 Apr  4 00:01 www.mydomain.com%3Alatest
root@prof394:/etc/resty-auto-ssl/storage/file# more www.mydomain.com%3Alatest 
{"cert_pem":"","privkey_pem":"","fullchain_pem":""}
```

and (almost an hour after that) after that moment, thousands of
`2017/04/04 00:57:12 [error] 2398#0: *1448383 [lua] ssl_certificate.lua:247: auto-ssl: could not get certificate for www.mydomain.com - using fallback - failed to convert certificate chain from PEM to DER: PEM_read_bio_X509_AUX() failed, context: ssl_certificate_by_lua*, client: 75.142.xx.xxx, server: 0.0.0.0:443`

**Comment by GUI** [comment]
Hm, strange--sorry for the trouble! I don't think I've seen this before, though. The "dehydrated succeeded, but no certs present" error is a pretty strange one to hit, since that usually indicates dehydrated reports completing successfully, but we can't find certs in the expected location dehydrated was supposed to create them in. A few questions:

- What version of lua-resty-auto-ssl was this under?
- Has this just happened for this one domain, or have you had it happen for any other domains?
- Did this specific domain ever successfully register (eg, maybe if you restarted nginx, did things suddenly start working)?
- Can you think of anything peculiar or different for this one domain, or is it pretty standard?

**Comment by luto** [comment]
Closing this issue as we're still waiting for feedback. In case this is still an active topic for you, please just reopen it and we'll gladly take a look.
