### ISSUE TITLE
auto-ssl: failed to run do_ssl: Interrupted system call

### ISSUE THREAD

**Issue by fibigerg** [GUI/lua-resty-auto-ssl#59]
Hi, those messages pops up in logs every few minutes. Do you have any idea why do_ssl gets interupted?

**Visitors receive fallback certificate while the error occurs. (That is invalid.)** 

```
[lua] ssl_certificate.lua:265: ssl_certificate(): auto-ssl: failed to run do_ssl: init_by_lua:10: Interrupted system call, context: ssl_certificate_by_lua*, client: 10.135.30.111, server: 0.0.0.0:443
```

![image](https://cloud.githubusercontent.com/assets/5537140/25008036/bccebd1e-2062-11e7-8ca9-fef1314926f2.png)

We run on Fedora 24 with Openresty installed from package. **This issue occures on two of our servers for SSL termination.**

We will appreciated any help. Thanks

**Comment by fibigerg** [comment]
This error occured first with lua-resty-auto-ssl update I did on 13th March 2017. According to our logs.

**Comment by fibigerg** [comment]
I have updated to v0.10.5 and the issue continues.

**Comment by fibigerg** [comment]
We use this initial block
```
# A DNS resolver must be defined for OCSP stapling to function.
  resolver 8.8.8.8 ipv6=off;

  # Initial setup tasks.
  init_by_lua_block {
    auto_ssl = (require "resty.auto-ssl").new()

        require "resty.auto-ssl.ssl_certificate"
    -- Define a function to determine which SNI domains to automatically handle
    -- and register new certificates for. Defaults to not allowing any domains,
    -- so this must be configured.
    auto_ssl:set("allow_domain", function(domain)
      domains = io.popen('ls /data/domains')
      for d in domains:lines() do
        if (domain == d) then
          return true
        end
        if (domain == "www." .. d) then
          return true
        end
        if (domain == "cdn." .. d) then
          return true
        end
        if (domain == "beta." .. d) then
          return true
        end
        if (domain == "production." ..d) then
          return true
        end
      end
      if ngx.re.match(domain, "^.+.(realm0|stage0|beta|test|production).(inspirum|inspishop|inspiweb).cz$", "ijo") then
        return true
      end
      return false
    end)

    auto_ssl:set("dir", "/data/certs/resty-auto-ssl")

    auto_ssl:init()
  }

  init_worker_by_lua_block {
    auto_ssl:init_worker()
  }
```

**Comment by GUI** [comment]
Sorry for the trouble! So were you successfully running a version prior to v0.10.4 where this error did not occur? Or was v0.10.4 the first version you ever ran?

The error backtrace does originate from the extra error handling we added in v0.10.4, but I'm not sure why this would be causing new issues (although it could be logging issues that were silently happening before). The error seems to indicate the process is unexpectedly getting killed, so do you know if nginx is being reloaded or restarted at these same times? If you're not sure, you can see how old the nginx worker processes are by `ps -A -o stime,command | grep nginx`.

**Comment by GUI** [comment]
So I was able to reproduce this, but only when nginx is fully restarted in combination with the `io.popen` usage in your `allow_domain` callback. Without `io.popen`, this doesn't seem to happen, and it also doesn't seem to happen when just reloading (SIGHUP) nginx. I suspect what's happening is that nginx is restarting the worker processes while they're blocked by the external `io.popen` call. I also suspect this was happening in previous versions, but wasn't being logged as an error until we added the additional error handling in v0.10.4.

Generally speaking, you'll want to try and avoid things like `io.popen` in OpenResty, since it's a blocking operation (so it will tie up the nginx worker process from serving other requests while it's executing). Internally we use [lua-resty-shell](https://github.com/juce/lua-resty-shell) to execute shell commands, which allows for a non-blocking approach to executing commands (it should also be handled more gracefully during nginx restarts). The `ls` command might be fast, so it may not be super-noticeable, but depending on how much traffic you get, you may also want to think about caching the results of `ls` (or other strategies for storing the allowed domains), so that you're not having to execute a shell command and access the disk for each HTTPS connection.

Here's an alternative implementation of your `allow_domain` callback, which uses our internal `run_command` helper to execute shell commands (via lua-resty-shell, so it won't block). This `run_command` isn't part of our documented API, but I don't foresee it changing anytime soon. 

```lua
  init_by_lua_block {
    auto_ssl = (require "resty.auto-ssl").new()

    -- Define a function to determine which SNI domains to automatically handle
    -- and register new certificates for. Defaults to not allowing any domains,
    -- so this must be configured.
    auto_ssl:set("allow_domain", function(domain)
      local run_command = require "resty.auto-ssl.utils.run_command"
      local ngx_re = require "ngx.re"

      local status, output, err = run_command("ls -1 /data/domains")
      if err then
        ngx.log(ngx.ERR, "allow_domain ls error: ", err)
      else
        local domains = ngx_re.split(output, "\n")
        for _, d in ipairs(domains) do
          if (domain == d) then
            return true
          end
          if (domain == "www." .. d) then
            return true
          end
          if (domain == "cdn." .. d) then
            return true
          end
          if (domain == "beta." .. d) then
            return true
          end
          if (domain == "production." ..d) then
            return true
          end
        end
      end
      if ngx.re.match(domain, "^.+.(realm0|stage0|beta|test|production).(inspirum|inspishop|inspiweb).cz$", "ijo") then
        return true
      end
      return false
    end)

    auto_ssl:set("dir", "/data/certs/resty-auto-ssl")

    auto_ssl:init()
  }
```

With these changes to your `allow_domain` callback, I can't reproduce the "Interrupted system call" error during nginx restarts anymore, but let me know if you're still seeing any issues.

**Comment by GUI** [comment]
Whoops, I made I typo in my original comment, but have updated it (you should use `shell_execute`, not `run_command` for non-blocking shell commands). So I haven't tested the above with the fixed `shell_execute` usage, but I think it should work.

**Comment by fibigerg** [comment]
Thank you again @GUI, your script works and I don't see any errors in the log after few day testing.

Do you have any suggestion for the caching strategy you mentioned?

**Comment by luto** [comment]
@fibigerg about the caching strategy: [Here is what we use](https://gist.github.com/luto/ff4c7ccd0b0c9c9a9fe8cde67179ed6a). I stripped it down quite a bit for you. It's a very simple setup, really - refreshing the list of valid domains is done by just reloading nginx. There is a potential race-condition for _very_ early requests in the startup process and it has not yet been load tested. Works for our current, rather small setup, though.

**Comment by luto** [comment]
This seems to be resolved, according to your comments. In case are any new problems arise, please feel free to re-open this issue. Thank you!

**Comment by fibigerg** [comment]
Thank you! We will look into it.
