### ISSUE TITLE
letsencrypt folder created as root

### ISSUE THREAD

**Issue by gregkare** [GUI/lua-resty-auto-ssl#6]
This looks similar to #4 but for the other directory created inside of `/etc/resty-auto-ssl`: `.acme-challenges/`, `conf.d/` and `config.sh` are created by root

**Comment by GUI** [comment]
Ah, sorry this slipped past me earlier, but thanks for pointing this out.

I think `conf.d` and `config.sh` being owned by root is okay, but we do need to make sure `.acme-challenges` is writable by the nginx worker user. I think we can perhaps fix this by shifting the initial mkdir for `.acme-challenges` into the init_worker phase (instead of init), but I'll try to look at getting this fixed in the next week or two. Our test environment also doesn't currently perform tests with a separate nginx worker user, so I'd also like to try and resolve that so we can better test the permissions setup in an automated fashion.

Thanks again for the report!

**Comment by gregkare** [comment]
No problem! I dealt with this with our config management tool. Thanks for this great project!

**Comment by GUI** [comment]
This should now fixed as part of the v0.8.2 release (and we now have some tests in our test suite that check file permissions when starting the master process as root and the worker processes as another user). Thanks for reporting this!

**Comment by mingfang** [comment]
@GUI I'm getting permission errors for config
``` err: /usr/local/openresty/luajit/bin/resty-auto-ssl/dehydrated: line 136: /etc/resty-auto-ssl/letsencrypt/config: Permission denied
```
