### ISSUE TITLE
Failed to set ocsp stapling

### ISSUE THREAD

**Issue by Vad1mo** [GUI/lua-resty-auto-ssl#70]
Hello, 

I see this error now. 

The certificate was obtained correctly a few minutes ago but the OCSP stapling isn't working.

`2017/05/15 13:43:06 [error] 27#27: *12 [lua] ssl_certificate.lua:212: set_cert(): auto-ssl: failed to set ocsp stapling for pascal.domain.com - continuing anyway - failed to get ocsp response: failed to validate OCSP response (http://ocsp.int-x3.letsencrypt.org/): OCSP response not successful (6: unauthorized), context: ssl_certificate_by_lua*, client: 84.84.104.165, server: 0.0.0.0:443`

I have some other sites running that are setup automatically all in the same way all working fine. This is actually the first time I encounter this type of error.

**Comment by luto** [comment]
Is this a permanent or temporary error? There are [some scenarios](https://community.letsencrypt.org/t/ocsp-error-request-failed-with-ocsp-status-6-http-ocsp-int-x3-letsencrypt-org/24446/6) on let's encrypts side, which can cause the OCSP response for newly issued certificates to be unavailable. Since you are in fact receiving an answer from the OCSP server this _might_ be the case here.
Please double check if this behavior vanishes a few minutes or hours after certificate issuance and tell us your results. Thank you!

**Comment by luto** [comment]
Closing this issue as we're still waiting for feedback. In case this is still an active topic for you, please just reopen it and we'll gladly take a look.
