### ISSUE TITLE
Error creating new authz :: DNS name does not have enough labels

### ISSUE THREAD

**Issue by brendon** [GUI/lua-resty-auto-ssl#72]
Hi there, I'm getting the following error. It looks like `MGMT.stjosephsotahuhu.school.nz` is getting truncated to `MGMT`. I'm not supplying the incoming URL of course, and this is a weird one. The URL does point at our server so it's not a spoof. Is this a bug?

```
2017/05/21 03:28:55 [error] 2802#2802: *57296 [lua] lets_encrypt.lua:32: issue_cert(): auto-ssl: dehydrated failed: env HOOK_SECRET=819183729a4fc828c017cc950cd53a76006640079aa1f24bd89e2bd6bac07d6e HOOK_SERVER_PORT=8999 /usr/share/nginx/luajit/share/lua/5.1/resty/auto-ssl/vendor/dehydrated --cron --no-lock --domain MGMT --challenge http-01 --config /etc/resty-auto-ssl/letsencrypt/config --hook /usr/share/nginx/luajit/share/lua/5.1/resty/auto-ssl/shell/letsencrypt_hooks status: 256 out: # INFO: Using main config file /etc/resty-auto-ssl/letsencrypt/config
# INFO: Using additional config file /etc/resty-auto-ssl/letsencrypt/conf.d/contact_email.sh
Processing mgmt
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for mgmt...
 err:   + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 400)

Details:
{
  "type": "urn:acme:error:malformed",
  "detail": "Error creating new authz :: DNS name does not have enough labels",
  "status": 400
}

, context: ssl_certificate_by_lua*, client: 47.72.146.130, server: 0.0.0.0:443
2017/05/21 03:28:55 [error] 2802#2802: *57296 [lua] ssl_certificate.lua:88: issue_cert(): auto-ssl: issuing new certificate failed: dehydrated failure, context: ssl_certificate_by_lua*, client: 47.72.146.130, server: 0.0.0.0:443
2017/05/21 03:28:55 [error] 2802#2802: *57296 [lua] ssl_certificate.lua:247: auto-ssl: could not get certificate for MGMT - using fallback - failed to get or issue certificate, context: ssl_certificate_by_lua*, client: 47.72.146.130, server: 0.0.0.0:443
2017/05/21 03:28:57 [error] 2802#2802: *57301 [lua] ssl_certificate.lua:247: auto-ssl: could not get certificate for MGMT.stjosephsotahuhu.school.nz - using fallback - failed to convert certificate chain from PEM to DER: PEM_read_bio_X509_AUX() failed, context: ssl_certificate_by_lua*, client: 47.72.146.130, server: 0.0.0.0:443
```

**Comment by luto** [comment]
That sounds weird. Would you mind answering a few questions about you setup?

1. Which version of openresty and auto-ssl are you running?
2. Can you please provide your access log? Which domains does it show?
3. Is there a search domain (`search` in `/etc/resolv.conf`) defined? is it `stjosephsotahuhu.school.nz` by any chance?

Thank you.

**Comment by brendon** [comment]
Yes definitely weird. I was wondering if it was to do with the capitalisation of the first part of the domain name?

1. `nginx version: openresty/1.11.2.2` and `lua-resty-auto-ssl 0.10.4-1`
2. I had to modify the access log to show full URL's but here's what I got when I ran `curl -k https://MGMT.stjosephsotahuhu.school.nz`
    `- - - [23/May/2017:22:44:16 +0000] "GET https://mgmt.stjosephsotahuhu.school.nz/ HTTP/1.1" 404 234 "-" "curl/7.43.0" 0.008`
3. In `/etc/resolv.conf` I have `search v6.spikeatschool.co.nz` which is the domain name for this server.

**Comment by GUI** [comment]
So just to double check, when you run `curl -k https://MGMT.stjosephsotahuhu.school.nz` directly yourself, do you get this same registration error? Or are you only seeing this from external requests? Because one thing to note is that by default, the domain lua-resty-auto-ssl will try to register is the SNI hostname that's part of the SSL connection, which can be different from the HTTP Host header (which might be what you're seeing in the nginx access logs). So I just want to make sure there's no weird issues with an external client setting an odd SNI hostname on the request.

If that's not the case, then this is puzzling. Based on the log output, it looks like we're passing `--domain MGMT` straight to the dehydrated.sh command, so the second part of the domain has gone missing by the time we pass it off. But I just did some quick local tests, and when I passed `MGMT.stjosephsotahuhu.school.nz` as the SNI hostname, then dehydrated tried to register that full `MGMT.stjosephsotahuhu.school.nz` domain in my case (but these were just some quick tests).

So a few more questions:

- Have you implemented a custom `request_domain` callback function in your configuration? This is the function that returns the domain we try to register, and by default it should return the SNI domain directly from an OpenResty call. But if you have a custom implementation, then this might explain how a different domain is cropping up.
- Do you have a custom `allow_domain` callback function that might somehow be modifying the domain variable? I don't think it should be possible to change the domain inside this function, but this is the only other place I can think where the domain variable we use internally might get modified.
- In your custom nginx logging, what variable are you using to log the hostname? If you're using something like $host, you might also try logging the [`$ssl_server_name` variable](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables), which will log the SNI hostname nginx is seeing. This would at least be a good sanity check to verify what nginx is receiving.

**Comment by brendon** [comment]
Thanks @GUI, I think your hunch about the SNI hostname might be correct because I've checked and my curl request didn't generate the same error. I've added logging for that and will check what comes up the next time the request occurs. I think what's happened is that school has set up a catchall domain record and pointed it to us. We don't actually respond on that URL, but I thought I'd report this just in case it was a bug anyway. It could be a buggy piece of equipment on their internal network making the request.

Once I confirm that I'll let them know, but also I'm not working on using the domain filtering feature to only issue cert's for domains we care about. :)

I'll keep you posted. And thanks again for the detailed responses! :D

**Comment by brendon** [comment]
I managed to find one! Among others that use the full domain though:

```
- - - [25/May/2017:10:13:40 +0000] "GET https://mgmt/secars/secars.dll?h=FC8B3D63F869682279CA51361E7C94474610CDC3CD7C0AAAADF212D65CEAC268AB1BF2F41CCEF0F6C5576515FF428D3A51A3E192EE6D92BD5E93023D71BA1D31D5CE46BCFD26AB77CDAE35F1967ABA40EA00199387579F23A3A82C6DA4B9DD79E9288464B1A4FA18D5EE54041869CD4208E2F9F52C7FF308AE321CE50B1B6B2F8F9C191F716F2B5B5A2D573BF32A1179E9E754F6CAE328082A0CEE1EBA4BB47A01134B9C2F38C4A375908CBBBF94F63F4ACE8E043BB5665A81CF83419559EA777D75803011A4D9E4D251B25E3C13889A1A4EABD358525FB5E684B6C8A7923FEDB0B2B96B5083F4E482370C6184F9DC5274E1A03A8080DCE21B81E8C873918FAFD76297720C902DF6CFF59B02B4C347932DDED7FC3510C308828BF0635A78A73877C50FC57B9006B202853D4D8D5AF0EF3A14853BA4ACAD398EEF62F66A6AD8EA8F96FD65AF19B84B6BC34477B16FB8AB926AE813DC4F95BF3290D07CE28227D9912E56B391B6CF2FAE28063AD7A0A2F224A014B92F80EBB783131E87BD18F0F2BB3D5EDE41BF88331A4EF26EAAAC55D318CE5312D5DC9F797C2513E941AE8765D37863C564FF5FC08C8CE80F82E5F3A30281E524B904DD6ECEBD934006A8C441486C57829620E9968635E606ACE86F60 HTTP/1.1" "MGMT" 404 207 "-" "-" 0.006
- - - [25/May/2017:10:13:41 +0000] "GET https://mgmt.stjosephsotahuhu.school.nz/secars/secars.dll?h=FC8B3D63F869682279CA51361E7C94474610CDC3CD7C0AAAADF212D65CEAC268AB1BF2F41CCEF0F6C5576515FF428D3A51A3E192EE6D92BD5E93023D71BA1D31D5CE46BCFD26AB77CDAE35F1967ABA40EA00199387579F23A3A82C6DA4B9DD79E9288464B1A4FA18D5EE54041869CD4208E2F9F52C7FF308AE321CE50B1B6B2F8F9C191F716F2B5B5A2D573BF32A1179E9E754F6CAE328082A0CEE1EBA4BB47A01134B9C2F38C4A375908CBBBF94F63F4ACE8E043BB5665A81CF83419559EA777D75803011A4D9E4D251B25E3C13889A1A4EABD358525FB5E684B6C8A7923FEDB0B2B96B5083F4E482370C6184F9DC5274E1A03A8080DCE21B81E8C873918FAFD76297720C902DF6CFF59B02B4C347932DDED7FC3510C308828BF0635A78A73877C50FC57B9006B202853D4D8D5AF0EF3A14853BA4ACAD398EEF62F66A6AD8EA8F96FD65AF19B84B6BC34477B16FB8AB5E53112D5A70D0AE0925007F5D6B052D912E56B391B6CF2FAE28063AD7A0A2F224A014B92F80EBB783131E87BD18F0F2BB3D5EDE41BF88331A4EF26EAAAC55D318CE5312D5DC9F797C2513E941AE8765D37863C564FF5FC08C8CE80F82E5F3A30281E524B904DD6ECEBD934006A8C441486C57829620E9968635E606ACE86F60 HTTP/1.1" MGMT.stjosephsotahuhu.school.nz" 404 234 "-" "-" 0.006
```

You can see the first one is sending the inappropriate SNI hostname. At least we got to the bottom of it. I'll notify the school to remove their catchall :)

Thanks again for your thorough help :)

**Comment by Victor-Lv** [comment]
I got the same error.
Then I was told by my friend that I set my domain name as "langlv.me" which will cause this problem. Prefix is must , only set top domain name will cause this problem.
So I solve it and set up success by setting the domain as "www.langlv.me" or "*.langlv.me"。
Hope it help you.
