### ISSUE TITLE
How to change the challenge port ?

### ISSUE THREAD

**Issue by waldo2188** [GUI/lua-resty-auto-ssl#78]
I have a setup where I cannot use 80 port and neither 443. 
I use 8080 and 4333 for SSL.

lua-resty-auto-ssl raised this a error : 

```
2017/06/21 12:03:48 [error] 16#16: *30 [lua] lets_encrypt.lua:40: issue_cert(): auto-ssl: dehydrated failed: env HOOK_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx HOOK_SERVER_PORT=8999 /usr/local/openresty/luajit/bin/resty-auto-ssl/dehydrated --cron --no-lock --domain sub-domain.exemple.org --challenge http-01 --config /etc/resty-auto-ssl/letsencrypt/config --hook /usr/local/openresty/luajit/bin/resty-auto-ssl/letsencrypt_hooks status: 256 out: # INFO: Using main config file /etc/resty-auto-ssl/letsencrypt/config
# INFO: Using additional config file /etc/resty-auto-ssl/letsencrypt/conf.d/custom.sh
Processing sub-domain.exemple.org
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for sub-domain.exemple.org...
 + Responding to challenge for sub-domain.exemple.org...
 err: ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:unauthorized",
    "detail": "Invalid response from http://sub-domain.exemple.org/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx [XXX.XXX.XXX.XXX]: 404",
    "status": 403
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "keyAuthorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "validationRecord": [
    {
      "url": "http://sub-domain.exemple.org/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "hostname": "sub-domain.exemple.org",
      "port": "80",
      "addressesResolved": [
        "XXX.XXX.XXX.XXX"
      ],
      "addressUsed": "XXX.XXX.XXX.XXX",
      "addressesTried": []
    }
  ]
})

```
We can see, in this log, the challenge with Let's Encrypt is made with the regular HTTP port (80), and fail.
How can I change this configuration, and replace the default port with 8080 ?

**Comment by GUI** [comment]
I don't think this will be possible. For security reasons, Let's Encrypt requires that the challenge take place over port 80 (when using the http-01 challenge mechanism, which is what lua-resty-auto-ssl uses). Basically, they need to verify that you own the server, and aren't running an unauthorized server on an unprivileged port. See https://community.letsencrypt.org/t/how-to-specify-a-port-different-from-443-for-the-dvsni-challenge/12753/2

The only alternative that works without ports 80 or 443, would be DNS based verification. That's not something lua-resty-auto-ssl currently implements, but it should be doable. The underlying [dehydrated.sh](https://github.com/lukas2511/dehydrated) library we use, supports this, so I think we'd mainly have to expose a custom hook that would allow you to implement your custom DNS update logic in the Lua code (that's not something we can automate fully like the HTTP verification, since this will depend on whether your DNS provider has programatic APIs and how they work).

If DNS validation would work for you, I'd be curious to know, just to gauge demand. Although, I'm not sure I'll have time to work on it personally, but pull requests are always welcome.

**Comment by waldo2188** [comment]
Thanks for your answer. 
Indeed, on the repo of dehydrated.sh, the issue [#227](https://github.com/lukas2511/dehydrated/issues/227) explain that another port than 80 is not a good idea. 

So I'll try another way to configure my Nginx. I think we are not numerous to face the same issue, so, maybe, don't waste your time on this issue.

**Comment by GUI** [comment]
Sounds good. I'll close this issue, then, but if there's interest in DNS support in the future, feel free to open a new issue.
