### ISSUE TITLE
OCSP responder returns bad HTTP status code (http://ocsp.int-x3.letsencrypt.org): 400

### ISSUE THREAD

**Issue by gregkare** [GUI/lua-resty-auto-ssl#79]
This looks like a different issue from #70 

This is a permanent issue, happening on multiple servers. We are running version 0.11.0-1 of lua-resty-auto-ssl and we do have a resolver set in the nginx config. Our setup works, except for the OCSP errors in the logs. We originally thought this was only happening for one domain, so we deleted it and got a new cert, but the issue happens still on every domain.

I tried to debug the `fullchain_der` and `ocsp_req` from `auto-ssl/ssl_certificate.lua` but it is binary. The `req.body` from the OCSP endpoint also contains binary, so something looks wrong.

Has anyone else had this issue? It started happening a few months ago, we didn't have it before. Any idea how to debug that issue? Thanks

Edit: Here's the full error line from the log:

```
2017/07/10 17:21:24 [error] 19066#0: *6 [lua] ssl_certificate.lua:221: set_cert(): auto-ssl: failed to set ocsp stapling for example.com - continuing anyway - failed to get ocsp response: OCSP responder returns bad HTTP status code (http://ocsp.int-x3.letsencrypt.org): 400
```

**Comment by luto** [comment]
OCSP encodes the requests and responses as ASN.1, which encoded in the binary DER format most of the time. Seeing a binary request and response is therefore normal. Even though I doubt that `ocsp.create_ocsp_request` would generate invalid requests: can you please share the value of `ocsp_req` as hex dump or base64 with us? That should be possible using [`ngx.encode_base64`](https://github.com/openresty/lua-nginx-module#ngxencode_base64).

**Comment by gregkare** [comment]
Thanks for your answer

Here's the `ocsp_req` as base64 for a test domain: `MFMwUTBPME0wSzAJBgUrDgMCGgUABBR+5mrncpqz/PiiIGRsFqEtYHEIXQQUqEpqYwR93brm0Tm3pkVl7/Oo7KECEgPm9BFOzTXMq27x5uEc1aZpoQ==`

I can reproduce the 400 from Let's Encrypt's OCSP server with the following curl request (with any data as the POST body):

```
curl -v -H 'Content-Type: application/ocsp-request' http://ocsp.int-x3.letsencrypt.org --data "anything"
```

**Comment by luto** [comment]
As you probably know 400 just means "Bad Request". Since `anything` isn't remotely a valid OCSP request, the let's encrypt server rightfully responds with, well, "Bad Request".

The big question is why it does that for a seemingly valid request generated by openresty/auto-ssl. I checked the base64 data you provided. It's at least valid ASN.1, seems to match the schema for OCSP requests. @GUI any ideas?

**Comment by gregkare** [comment]
Are we the only ones getting this issue? Thanks :)

**Comment by GUI** [comment]
@gregkare: Apologies for the delay. I've just checked the last week of our production logs to see if we've experienced any failures like this, but I only found one failure of a 503 response during [this Let's Encrypt partial outage](https://letsencrypt.status.io/pages/incident/55957a99e800baa4470002da/596d2bf70b000d7d48002dbc). So if you're seeing this consistently, I'm not exactly sure what would be causing it, but let's see if we can figure out what's going on...

As a first step to debugging this, could you see if you're able to get a successful OCSP response using the `openssl` command line tool? On the server where this certificate is located, you can do this by:

1. Extract the OCSP URL from the certificate:

   ```
   sudo openssl x509 -in /etc/resty-auto-ssl/letsencrypt/certs/YOUR_DOMAIN/cert.pem -noout -ocsp_uri
   ```

2. Run the `openssl ocsp` command using the OCSP URL found:

   ```
   sudo openssl ocsp -no_nonce \
     -issuer /etc/resty-auto-ssl/letsencrypt/certs/YOUR_DOMAIN/chain.pem \
     -verify_other /etc/resty-auto-ssl/letsencrypt/certs/YOUR_DOMAIN/chain.pem \
     -cert /etc/resty-auto-ssl/letsencrypt/certs/YOUR_DOMAIN/cert.pem \
     -url OCSP_URL_HERE -header "Host" "OCSP_HOST_HERE"
   ```

   The last line should be something like `-url http://ocsp.int-x3.letsencrypt.org -header "Host" "ocsp.int-x3.letsencrypt.org"` (note the url includes `http://` while the `Host` header does not). Interestingly, I do get 400 responses back if I mess up the Host header, but that may be a red herring, since I'm not sure how that would be incorrect in our request.

If that command succeeds, you should see something like:

```
Response verify OK
/etc/resty-auto-ssl/letsencrypt/certs/YOUR_DOMAIN/cert.pem: good
	This Update: Jul 22 16:00:00 2017 GMT
	Next Update: Jul 29 16:00:00 2017 GMT
```

If the command succeeds, then that might help pinpoint the issue to something lua-resty-auto-ssl is doing that's different from the request OpenSSL makes. But if the command fails, then that might point to some other issue that's specific to this environment (eg, like some proxy in the network environment munging the binary data on the outgoing OCSP request).

**Comment by gregkare** [comment]
Thanks for your reply. I just got a successful response when running the `openssl ocsp` command. I'll try to debug the resty-auto-ssl request

**Comment by GUI** [comment]
Well, at least that helps narrow things down. If you're comfortable hacking on the source code, a few other ideas for debugging:

- Add [a line](https://github.com/GUI/lua-resty-auto-ssl/blob/v0.11.0/lib/resty/auto-ssl/ssl_certificate.lua#L137) to log the length of the `ocsp_req` variable (`ngx.log(ngx.ERR, "ocsp_req len: " .. #ocsp_req`)
- `create_ocsp_request` accepts a [`max_len` argument](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ocsp.md#create_ocsp_request), which "usually defaults to 4KB." I think that should be plenty big for the OCSP request data, but you could try explicitly setting this in case the default in your environment is somehow smaller (or if the logged length is right at 4KB already). So you could [change this line](https://github.com/GUI/lua-resty-auto-ssl/blob/v0.11.0/lib/resty/auto-ssl/ssl_certificate.lua#L133) to something like `local ocsp_req, ocsp_request_err = ocsp.create_ocsp_request(fullchain_der, 8192)`. (Although, in reviewing nginx's tests, it looks like it should actually return an error if the buffer size is too small, so this might not be it.)
- If you can share what domain you're experiencing this on, I can also try to debug this, since OCSP only involves the public certificate (you're also welcome to email me directly if you'd prefer not to share the domain here).
  - Similarly, if you want to share the contents of the `/etc/resty-auto-ssl/letsencrypt/certs/YOUR_DOMAIN/fullchain.pem` (and again, this would be your public certificate only, not your private key), then we could put together a very simple test case, since that should be the only input required for our OCSP stapling (we [translate it to DER format](https://github.com/GUI/lua-resty-auto-ssl/blob/v0.11.0/lib/resty/auto-ssl/ssl_certificate.lua#L9), and then that should be the [only input](https://github.com/GUI/lua-resty-auto-ssl/blob/v0.11.0/lib/resty/auto-ssl/ssl_certificate.lua#L125)).

**Comment by pdr** [comment]
I've seen this happen during the latest LetsEncrypt outage as well, but no longer.

**Comment by Snowmanko** [comment]
I am having same problem.

**Comment by gregkare** [comment]
@GUI I have been able to successfully run the same request that resty-auto-ssl is doing using curl with the same binary data (I printed it as Base64 in `ssl_certificate.lua` and then decoded it into a file). The test domain is 5stage.karekinian.com, the `ocsp_req` len is 85. The base64 encoded OCSP request is `MFMwUTBPME0wSzAJBgUrDgMCGgUABBR+5mrncpqz/PiiIGRsFqEtYHEIXQQUqEpqYwR93brm0Tm3pkVl7/Oo7KECEgNRX8zEHuS3GQWUu1yiv3Q4Fg==`. Changing the max_length didn't change anything, since the `ocsp_req` is small.

For reference here's my successful curl request with the oscp_req saved as `test.bin`:

```
curl -v -H 'Content-Type: application/ocsp-request' http://ocsp.int-x3.letsencrypt.org --data-binary @test.bin
```

I don't see anything wrong with the `httpc:request_uri` call in https://github.com/GUI/lua-resty-auto-ssl/blob/v0.11.0/lib/resty/auto-ssl/ssl_certificate.lua#L141, so it looks like something about the binary data itself is wrong, even though it works with my request using curl

Here's the fullchain for this domain: 

```
-----BEGIN CERTIFICATE-----
MIIGDTCCBPWgAwIBAgISA1FfzMQe5LcZBZS7XKK/dDgWMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xNzA4MjcxMzM0MDBaFw0x
NzExMjUxMzM0MDBaMCAxHjAcBgNVBAMTFTVzdGFnZS5rYXJla2luaWFuLmNvbTCC
AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK+fVbJOnoeNoI1x3hwenw3N
a7vc4Z0ec+lIqpnvXvSMumeaD/SlnxdowIBrLhy1nLDIon6IKxpYrcjC2ac/HdHT
vi4JNg5rfSBgtATpw+EQ1Ut9ss+Tq9DVQKu4YttmMQH0dgfLCBYDDmtRrzIst92I
JOX3W6ulTYJpkOI4GvBFWqLnqyOxCJzf5Hjy6ABC5PepW5LkitEB1oBc65lrbAuR
sIGeb7TUSQDc8GMl0OimuYIg2HjytSJOT9bIu6u9rl3yuoX7W/OxTTdFMvk2kPfI
Rojb3nl3YFKLe08yuHylw87VacV9s3h/83LCajfd5NA/NWMEQGDoJE74aqzdNGLk
RTZ8P0VuLFl8LoY1GNmQzosvsuSvYCJLb94CE1c3aPGODY0yN7YtGlE7A96dnyUE
otn59Wz40QNXXtG04cHbPkBF2YF1rY3LIknGizuGYIQF/3kaa5lBWpwdHvDcHNcU
2WKl4d3xtG3eGMoptdu0KakMPqyPISqmMJu9zODdLLblENMPnKrhChICgV7tuEEJ
szqcxxgTwnuPjYo4sBF3NADIcoEJeKVIXlQvGX+RAVCl9f564ShhQ6E3v5kmyVQP
0vkbM0JORxO8QZbS3CSuyA02rc897Ua+Y3N6L73m/JXYOXf5PPnE/XmZJdvNLE6h
Qc0vdvIrWCELnCnlQcADAgMBAAGjggIVMIICETAOBgNVHQ8BAf8EBAMCBaAwHQYD
VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
BBYEFDAWPdVQWDpduNb/DzPf0xtGgKiIMB8GA1UdIwQYMBaAFKhKamMEfd265tE5
t6ZFZe/zqOyhMG8GCCsGAQUFBwEBBGMwYTAuBggrBgEFBQcwAYYiaHR0cDovL29j
c3AuaW50LXgzLmxldHNlbmNyeXB0Lm9yZzAvBggrBgEFBQcwAoYjaHR0cDovL2Nl
cnQuaW50LXgzLmxldHNlbmNyeXB0Lm9yZy8wIAYDVR0RBBkwF4IVNXN0YWdlLmth
cmVraW5pYW4uY29tMIH+BgNVHSAEgfYwgfMwCAYGZ4EMAQIBMIHmBgsrBgEEAYLf
EwEBATCB1jAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcw
gasGCCsGAQUFBwICMIGeDIGbVGhpcyBDZXJ0aWZpY2F0ZSBtYXkgb25seSBiZSBy
ZWxpZWQgdXBvbiBieSBSZWx5aW5nIFBhcnRpZXMgYW5kIG9ubHkgaW4gYWNjb3Jk
YW5jZSB3aXRoIHRoZSBDZXJ0aWZpY2F0ZSBQb2xpY3kgZm91bmQgYXQgaHR0cHM6
Ly9sZXRzZW5jcnlwdC5vcmcvcmVwb3NpdG9yeS8wDQYJKoZIhvcNAQELBQADggEB
AI1HKdB3gQP9zSzMSIp3zGPumQc6sD3xqoG2b0IPNWDzeQjN+41mrKWq8FuDG5sG
kpH9Z2W5vfTmemU4WD7hyWpewAZLueVDgXKSu5rry64fz9Wyj+kGhrYM1jSG59Wf
1rRjIWfytjjpiW7VoW/bvud2JHJpBiQM/PjLUVVLHgqjX52mRwylMdDPSuIlPym4
wu4s2IyCcZjI6Xz/cC6HZW/geftJqLEmRgDX2Y9yMjF4N3m0Y8kx99/O/nhn5u33
4nAKXP8Ju03HFjvB17LgyMIj/pBmTFNgmtq4AtleFSWIIw/yFVJiVGuTns9295Jl
L23LOTQypOfyDVJ7FCFZvTo=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----
```

**Comment by gregkare** [comment]
I think the issue was resty-http after all. We were on a really old version (0.0.4), updating to 0.11.0-0 seems to have fixed the issue on our staging server

**Comment by GUI** [comment]
@gregkare: Ahh, I hadn't thought of the lua-resty-http dependency version. Sorry for the trouble, but thanks so much for debugging this and getting to the bottom of it! I'll try to do some further testing of lua-resty-http to figure out what our minimum version is and bump our rockspec file to ensure we have the appropriate version.

**Comment by gregkare** [comment]
@GUI No problem! We're now running this in production, OCSP stapling is now working with the latest resty-http
