### ISSUE TITLE
Certificates not saved

### ISSUE THREAD

**Issue by gjongenelen** [GUI/lua-resty-auto-ssl#8]
Hi,

I'm experimenting with auto-ssl, but found a few problems. 
`7/19/2016 10:07:00 AM2016/07/19 08:07:00 [notice] 11#0: [lua] ssl_certificate.lua:67: issue_cert(): auto-ssl: issuing new certificate for domain.com, context: ssl_certificate_by_lua*, client: 10.42.225.194, server: 0.0.0.0:443
7/19/2016 10:07:01 AM2016/07/19 08:07:01 [warn] 11#0: [lua] lets_encrypt.lua:37: issue_cert(): auto-ssl: letsencrypt.sh succeeded, but certs still missing from storage - trying to manually copy - domain: domain.com, context: ssl_certificate_by_lua*, client: 10.42.225.194, server: 0.0.0.0:443
7/19/2016 10:07:01 AM2016/07/19 08:07:01 [error] 11#0: [lua] lets_encrypt.lua:48: issue_cert(): auto-ssl: letsencrypt.sh manual hook.sh failed: env HOOK_SECRET=069a6df73827f25a7a090eda215c370fd926e2c3f2998a31a268247286167443 /usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl/shell/letsencrypt_hooks deploy_cert domain.com /etc/resty-auto-ssl/letsencrypt/certs/domain.com/privkey.pem /etc/resty-auto-ssl/letsencrypt/certs/domain.com/cert.pem /etc/resty-auto-ssl/letsencrypt/certs/domain.com/fullchain.pem status: 256 out: nil err: + HANDLER=deploy_cert
7/19/2016 10:07:01 AM+ shift
7/19/2016 10:07:01 AM+ deploy_cert domain.com /etc/resty-auto-ssl/letsencrypt/certs/domain.com/privkey.pem /etc/resty-auto-ssl/letsencrypt/certs/domain.com/cert.pem /etc/resty-auto-ssl/letsencrypt/certs/domain.com/fullchain.pem
7/19/2016 10:07:01 AM/usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl/shell/letsencrypt_hooks: line 35: 5: unbound variable
7/19/2016 10:07:01 AM, context: ssl_certificate_by_lua*, client: 10.42.225.194, server: 0.0.0.0:443
7/19/2016 10:07:01 AM2016/07/19 08:07:01 [error] 11#0: [lua] ssl_certificate.lua:70: issue_cert(): auto-ssl: issuing new certificate failed: letsencrypt.sh failure, context: ssl_certificate_by_lua*, client: 10.42.225.194, server: 0.0.0.0:443
7/19/2016 10:07:01 AM2016/07/19 08:07:01 [error] 11#0: [lua] ssl_certificate.lua:238: ssl_certificate(): auto-ssl: could not get certificate for domain.com - using fallback - failed to get or issue certificate, context: ssl_certificate_by_lua*, client: 10.42.225.194, server: 0.0.0.0:443
7/19/2016 10:07:01 AM2016/07/19 08:07:01 [info] 11#0: *63 SSL_do_handshake() failed (SSL: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:SSL alert number 48) while SSL handshaking, client: 10.42.225.194, server: 0.0.0.0:443
7/19/2016 10:07:01 AM2016/07/19 08:07:01 [crit] 11#0: *63 SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking, client: 10.42.225.194, server: 0.0.0.0:443
`

Because it is using its fallback cert I get an Privacy Error.

Two things got my attention: the **letsencrypt_hooks: line 35: 5: unbound variable** and **letsencrypt.sh succeeded, but certs still missing from storage**.

I'm using a Redis-storageadapter between multiple servers. 

What could I be doing wrong?

**Comment by GUI** [comment]
Was this fixed by explicitly setting the redis port (related to https://github.com/GUI/lua-resty-auto-ssl/pull/9)? Or are you still experiencing problems?

This does uncover a compatibility issue between this `letsencrypt.sh succeeded, but certs still missing from storage - trying to manually copy` edge-case and compatibility with the latest letsencrypt.sh updates (from https://github.com/GUI/lua-resty-auto-ssl/pull/7). However, I think that edge-case is only hit if something with the storage doesn't work as expected earlier on, so that's why I'm wondering if specifying a port on the redis adapter fixed this issue for you. If not, let me know, since I think there may still be something else going on with the storage.

In any case, we do need to fix our compatibility with the latest letsencrypt.sh client when dealing with this edge-case. I'll also try to add some better tests around this scenario and some better error handling. Thanks for catching this!

**Comment by gjongenelen** [comment]
Hi, no, #9 did not fix my problems. Im also noticing that i get the following output after clearing my redis and recreating my nginx-container:
`Processing domain.com
+ Checking domain name(s) of existing cert... unchanged.
+ Checking expire date of existing cert...
+ Valid till Oct 17 06:11:00 2016 GMT (Longer than 30 days). Skipping renew!`

But I'm still getting the error **certs still missing from storage**. Where is he getting the certificates from then?

I'm going to investigate more next week. Because it would be really cool if this would work correctly!

**Comment by GUI** [comment]
Okay, I think this might still be related to the original Redis port issue that caused the failure in storing the data. I've fixed the issue around "certs still missing from storage" in master, which I believe should resolve this issue. I'll try to get v0.8.3 pushed to luarocks later today with those fixes.

Alternatively, if you'd like to test this theory now, you could try clearing your redis data *and* wiping the contents of `/etc/resty-auto-ssl/letsencrypt/certs` on any of your machines. That should really reset things so a new certificate will be registered and stored in redis with your port fix in place (basically, as long as the previous cert is present in `/etc/resty-auto-ssl/letsencrypt/certs`, you're going to be hitting the "certs still missing from storage" bug in v0.8.2). Or again, if you want to wait until v0.8.3 is out (hopefully later today), I believe upgrading to that should fix all this.

Sorry for all the trouble caused by the typo around the redis port! But thanks for reporting this and helping debug.

**Comment by gjongenelen** [comment]
I saw your commits. I will try to test this as fast as possible as it is released. 

No problem, thanks for your quick replies!

**Comment by GUI** [comment]
@gjongenelen: Okay, I just pushed v0.8.3. Can you try upgrading to this version via luarocks? I think it should hopefully fix things in your current installation. But please let me know if you're still running into any issues.

**Comment by gjongenelen** [comment]
I tested it and it looks like it is working properly. 

Thank you very much. This project is saving me a lot of money!

**Comment by GUI** [comment]
Perfect, glad that did the trick. Thanks for your patience and help in uncovering these couple of bugs!
