### ISSUE TITLE
bad light userdata pointer

### ISSUE THREAD

**Issue by meyskens** [GUI/lua-resty-auto-ssl#84]
I'm having an issue getting the module to work on arm64/aarch64. I get the following error: 
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [error] init_by_lua error: bad light userdata pointer
stack traceback:
	[C]: at 0xffffb6139434
	[C]: in function 'require'
	/usr/local/share/lua/5.1/resty/auto-ssl/storage.lua:6: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/resty/auto-ssl/init_master.lua:89: in function 'setup_storage'
	/usr/local/share/lua/5.1/resty/auto-ssl/init_master.lua:102: in function 'init_master'
	/usr/local/share/lua/5.1/resty/auto-ssl.lua:64: in function 'init'
	init_by_lua:41: in main chunk
nginx: configuration file /etc/nginx/nginx.conf test failed
```

This seems a code specific issue that only happens on arm64/aarch64.

**Comment by luto** [comment]
Since `cjson` is [part of openresty](https://openresty.org/en/lua-cjson-library.html) by now, this is probably a bug within `cjson` or openresty itself. If you get a minimal example running, it would probably be nice to report it [to openresty directly](https://github.com/openresty/lua-cjson/issues). Sadly I don't have access to any arm64 hardware myself.

**Comment by GUI** [comment]
See #85 for further discussion, but should hopefully be addressed in ARM environments (or anywhere cjson can't be used) by using the new dkjson json adapter: https://github.com/GUI/lua-resty-auto-ssl#json_adapter
